name: Pomodoro
version: '1.0.0'
main: org.encinet.pomodoro.Pomodoro
description: A highly customizable, GUI-driven Pomodoro timer to help players manage their time and stay focused in Minecraft.
api-version: '1.21'
authors: [ Noctiro ]
website: https://github.com/noctiro/Pomodoro
folia-supported: true
dependencies:
  - name: packetevents
    required: true
    load: BEFORE
